version: '3.8'
services:
  tests:
    build:
      context: .
      dockerfile: src/backend/Dockerfile.test
    env_file:
      - ./src/backend/.env
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development
